services:
  - type: web
    name: myapp-server
    env: docker
    dockerContext: ./tech-int3-server
    dockerFilePath: ./Dockerfile 
    plan: free

  - type: web
    name: myapp-client
    env: docker
    dockerContext: .
    dockerFilePath: ./Dockerfile
    plan: free
    envVars:
      - key: BACKEND_URL
        fromService:
          name: myapp-server
          type: web
          property: host